name: ChatFormatter
main: com.github.neapovil.chatformatter.ChatFormatter
version: 1.0.0
api-version: 1.19
author: Neapovil
website: https://github.com/Neapovil/chat-formatter
depend:
  - CommandAPI
permissions:
  chatformatter.command:
    default: op
